# Generated by Django 2.1.1 on 2018-09-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='recomendacoes',
            field=models.CharField(default='oi', max_length=255),
            preserve_default=False,
        ),
    ]
