# Generated by Django 2.1 on 2018-09-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_livro_recomendacoes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='editora',
            options={'verbose_name': 'Editora', 'verbose_name_plural': 'Editoras'},
        ),
        migrations.AlterModelOptions(
            name='livro',
            options={'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
        migrations.AlterModelOptions(
            name='loja',
            options={'verbose_name': 'Loja', 'verbose_name_plural': 'Lojas'},
        ),
        migrations.RemoveField(
            model_name='livro',
            name='recomendacoes',
        ),
        migrations.AddField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='avaliacao',
            field=models.FloatField(),
        ),
    ]
